apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lap-gateway.name" . }}-config
  labels:
    {{- include "lap-gateway.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: "{{ $v }}"
{{- end }}
