apiVersion: v1
kind: Service
metadata:
  name: lap-gateway
  namespace: lap-system
  labels:
    app.kubernetes.io/name: lap-gateway
spec:
  selector:
    app.kubernetes.io/name: lap-gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
