apiVersion: v1
kind: Service
metadata:
  name: lap-tool-service
  namespace: lap-system
  labels:
    app.kubernetes.io/name: lap-tool
spec:
  selector:
    app.kubernetes.io/name: lap-tool
  ports:
    - name: http
      port: 9000
      targetPort: http
