global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "lap-gateway"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["gateway:8000"]
